"""init schema

Revision ID: ebfd4b8f1b96
Revises: 
Create Date: 2026-09-06 17:47:58.043722
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = 'ebfd4b8f1b96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_executions_input_hash'), 'ai_executions', ['input_hash'], unique=False)
    op.create_index('ix_ai_executions_stage', 'ai_executions', ['pipeline_stage'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'date', name='uq_digest_kind_date')
    )
    op.create_table('objects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('GAME_ENGINE', 'RENDERING_ENGINE', 'WEB_ENGINE', 'GRAPHICS_RUNTIME', 'GRAPHICS_API', 'GPU_VENDOR', 'PLATFORM', 'DCC', 'TOOL', 'STANDARD', 'TECHNOLOGY', name='object_type', native_enum=False, length=64), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('github_repo', sa.String(length=256), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_domain'), 'objects', ['domain'], unique=False)
    op.create_index(op.f('ix_objects_slug'), 'objects', ['slug'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_slug', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Enum('VERSION_RELEASE', 'FEATURE_ADDED', 'CAPABILITY_ENABLED', 'ARCHITECTURE_CHANGE', 'SPEC_CHANGE', 'PERFORMANCE_CHANGE', 'QUALITY_CHANGE', 'TOOLCHAIN_CHANGE', 'TECHNOLOGY_ADOPTION', 'BREAKING_CHANGE', name='event_type', native_enum=False, length=64), nullable=False),
    sa.Column('change_signal', sa.Enum('NEW', 'EXPAND', 'ADOPT', 'MATURE', 'SPEC', 'PERF', 'BREAK', name='change_signal', native_enum=False, length=64), nullable=False),
    sa.Column('change', sa.Text(), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('who_should_care', sa.Text(), nullable=False),
    sa.Column('impact_level', sa.Enum('CRITICAL', 'HIGH', 'NOTABLE', name='impact_level', native_enum=False, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impact_capability', sa.Integer(), nullable=False),
    sa.Column('impact_engineering', sa.Integer(), nullable=False),
    sa.Column('impact_adoption', sa.Integer(), nullable=False),
    sa.Column('impact_scope', sa.Integer(), nullable=False),
    sa.Column('impact_confidence', sa.Integer(), nullable=False),
    sa.Column('maturity_from', sa.Enum('RESEARCH', 'PROTOTYPE', 'OPEN_SOURCE', 'SDK', 'STANDARD', 'ENGINE_INTEGRATION', 'PRODUCTION', 'CROSS_PLATFORM', 'MAINSTREAM', name='maturity_stage', native_enum=False, length=64), nullable=True),
    sa.Column('maturity_to', sa.Enum('RESEARCH', 'PROTOTYPE', 'OPEN_SOURCE', 'SDK', 'STANDARD', 'ENGINE_INTEGRATION', 'PRODUCTION', 'CROSS_PLATFORM', 'MAINSTREAM', name='maturity_stage', native_enum=False, length=64), nullable=True),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('title_embedding', Vector(dim=256), nullable=True),
    sa.Column('change_embedding', Vector(dim=256), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'VERIFIED', 'PUBLISHED', 'REJECTED', 'MERGED', name='event_status', native_enum=False, length=64), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_object_id'), 'events', ['object_id'], unique=False)
    op.create_index('ix_events_published_at', 'events', ['published_at'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('GITHUB_RELEASE', 'GITHUB_PR', 'GITHUB_ISSUE', 'GITHUB_DISCUSSION', 'RSS', 'RELEASE_NOTES', 'OFFICIAL_BLOG', 'SPEC_REGISTRY', 'DOCUMENTATION', 'ROADMAP', 'CONFERENCE', 'COMMUNITY', 'HTML', name='source_type', native_enum=False, length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_cursor', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_object_id'), 'sources', ['object_id'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('important_event_count', sa.Integer(), nullable=False),
    sa.Column('unique_object_count', sa.Integer(), nullable=False),
    sa.Column('unique_vendor_count', sa.Integer(), nullable=False),
    sa.Column('platform_expansion_count', sa.Integer(), nullable=False),
    sa.Column('maturity_transition_count', sa.Integer(), nullable=False),
    sa.Column('adoption_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('ACCELERATING', 'GROWING', 'STABLE', 'COOLING', 'RESEARCH_HEAVY', name='trend_state', native_enum=False, length=64), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'window_days', 'snapshot_date', name='uq_trend_topic_window')
    )
    op.create_index(op.f('ix_trend_snapshots_topic_id'), 'trend_snapshots', ['topic_id'], unique=False)
    op.create_table('event_topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('relation', sa.Enum('DIRECT', 'AFFECTED', 'ENABLED', 'ADOPTED', 'RELATED', name='event_topic_relation', native_enum=False, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'topic_id', name='uq_eventtopic_event_topic')
    )
    op.create_index(op.f('ix_event_topics_event_id'), 'event_topics', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_topics_topic_id'), 'event_topics', ['topic_id'], unique=False)
    op.create_table('raw_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter_status', sa.Enum('NEW', 'IGNORED', 'CANDIDATE', 'PROCESSED', name='raw_filter_status', native_enum=False, length=64), nullable=False),
    sa.Column('filter_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_rawitem_source_external')
    )
    op.create_index(op.f('ix_raw_items_filter_status'), 'raw_items', ['filter_status'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_index('ix_rawitem_canonical_url', 'raw_items', ['canonical_url'], unique=False)
    op.create_index('ix_rawitem_content_hash', 'raw_items', ['content_hash'], unique=False)
    op.create_index('ix_rawitem_filter_status', 'raw_items', ['filter_status'], unique=False)
    op.create_table('event_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('raw_item_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('PRIMARY', 'OFFICIAL', 'SUPPORTING', 'COMMUNITY', 'DISCOVERY', name='event_source_role', native_enum=False, length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'raw_item_id', name='uq_eventsource_event_rawitem')
    )
    op.create_index(op.f('ix_event_sources_event_id'), 'event_sources', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_sources_raw_item_id'), 'event_sources', ['raw_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_sources_raw_item_id'), table_name='event_sources')
    op.drop_index(op.f('ix_event_sources_event_id'), table_name='event_sources')
    op.drop_table('event_sources')
    op.drop_index('ix_rawitem_filter_status', table_name='raw_items')
    op.drop_index('ix_rawitem_content_hash', table_name='raw_items')
    op.drop_index('ix_rawitem_canonical_url', table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_filter_status'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_index(op.f('ix_event_topics_topic_id'), table_name='event_topics')
    op.drop_index(op.f('ix_event_topics_event_id'), table_name='event_topics')
    op.drop_table('event_topics')
    op.drop_index(op.f('ix_trend_snapshots_topic_id'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_sources_object_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index('ix_events_published_at', table_name='events')
    op.drop_index(op.f('ix_events_object_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_objects_slug'), table_name='objects')
    op.drop_index(op.f('ix_objects_domain'), table_name='objects')
    op.drop_table('objects')
    op.drop_table('digests')
    op.drop_index('ix_ai_executions_stage', table_name='ai_executions')
    op.drop_index(op.f('ix_ai_executions_input_hash'), table_name='ai_executions')
    op.drop_table('ai_executions')
    # ### end Alembic commands ###
