#!/usr/bin/env python3
"""Generate config/objects/*.yaml and config/topics/*.yaml from the monitoring
scope defined in the Content & Intelligence Spec v0.1 (sections 4-11, 15).

Object scope is code-reviewable here; the YAML files are the runtime truth.
Run: uv run python tools/gen_configs.py
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OBJECTS_DIR = ROOT / "config" / "objects"
TOPICS_DIR = ROOT / "config" / "topics"

GITHUB_PR_KEYWORDS = [
    "vulkan", "metal", "dx12", "webgpu", "opengl", "bindless", "ray tracing",
    "mesh shader", "render graph", "renderer", "backend", "shader", "gpu",
    "performance", "graphics",
]


def gh(repo: str, poll: int = 60) -> dict:
    return {"type": "github_release", "repo": repo, "poll_interval": poll}


def gh_pr(repo: str, keywords: list[str] | None = None, poll: int = 120) -> dict:
    return {
        "type": "github_pr",
        "repo": repo,
        "poll_interval": poll,
        "watch": {"pull_requests": {"merged_only": True, "keywords": keywords or GITHUB_PR_KEYWORDS}},
    }


def rss(url: str, poll: int = 120, stype: str = "rss") -> dict:
    return {"type": stype, "url": url, "poll_interval": poll}


def blog(url: str, poll: int = 120) -> dict:
    return {"type": "official_blog", "url": url, "poll_interval": poll}


def notes(url: str, poll: int = 360) -> dict:
    return {"type": "release_notes", "url": url, "poll_interval": poll}


def registry(url: str, poll: int = 360) -> dict:
    return {"type": "spec_registry", "url": url, "poll_interval": poll}


def obj(id: str, name: str, type: str, domain: str, description: str = "",
        official_url: str | None = None, github_repo: str | None = None,
        aliases: list[str] | None = None, sources: list[dict] | None = None) -> dict:
    return {
        "id": id, "name": name, "type": type, "domain": domain,
        "description": description, "official_url": official_url,
        "github_repo": github_repo, "aliases": aliases or [],
        "sources": sources or [],
    }


CHROME_BLOG = "https://blog.chromium.org/feeds/posts/default?alt=rss"
ANDROID_BLOG = "https://android-developers.googleblog.com/feeds/posts/default?alt=rss"
NVIDIA_BLOG = "https://developer.nvidia.com/blog/feed/"
GPUOPEN_BLOG = "https://gpuopen.com/feed/"
DIRECTX_BLOG = "https://devblogs.microsoft.com/directx/feed/"
PHORONIX = "https://www.phoronix.com/rss.php"

OBJECTS: list[dict] = [
    # ---------------------------------------------------------------- Engine: game
    obj("unreal-engine", "Unreal Engine", "game_engine", "engine",
        "Epic Games' AAA game engine.", "https://www.unrealengine.com",
        aliases=["UE", "UE5", "Unreal"],
        sources=[notes("https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-5.6-release-notes")]),
    obj("unity", "Unity", "game_engine", "engine",
        "Unity real-time development platform.", "https://unity.com",
        aliases=["Unity3D"],
        sources=[notes("https://unity.com/releases/editor/whats-new"), rss("https://blog.unity.com/feed", stype="official_blog")]),
    obj("cocos-creator", "Cocos Creator", "game_engine", "engine",
        "Cross-platform 2D/3D game engine focused on mobile and mini-games.",
        "https://www.cocos.com/en/creator", github_repo="cocos/cocos-engine",
        aliases=["Cocos", "CocosEngine"],
        sources=[gh("cocos/cocos-engine")]),
    obj("godot", "Godot", "game_engine", "engine",
        "Free and open-source 2D/3D game engine.", "https://godotengine.org",
        github_repo="godotengine/godot",
        sources=[gh("godotengine/godot"), rss("https://godotengine.org/rss.xml", stype="official_blog")]),
    obj("o3de", "O3DE", "game_engine", "engine",
        "Open 3D Engine, an Apache-licensed AAA engine.", "https://o3de.org",
        github_repo="o3de/o3de", sources=[gh("o3de/o3de")]),
    obj("flax-engine", "Flax Engine", "game_engine", "engine",
        "Multi-platform 3D game engine with C# scripting.", "https://flaxengine.com",
        github_repo="FlaxEngine/FlaxEngine", sources=[gh("FlaxEngine/FlaxEngine")]),
    obj("bevy", "Bevy", "game_engine", "engine",
        "Rust data-driven game engine built on an ECS.", "https://bevy.org",
        github_repo="bevyengine/bevy",
        sources=[gh("bevyengine/bevy"), rss("https://bevy.org/atom.xml", stype="official_blog")]),
    obj("defold", "Defold", "game_engine", "engine",
        "Free 2D game engine with Lua scripting.", "https://defold.com",
        github_repo="defold/defold",
        sources=[gh("defold/defold"), rss("https://defold.com/feed.xml", stype="official_blog")]),
    obj("stride", "Stride", "game_engine", "engine",
        "Open-source C# game engine (formerly Xenko).", "https://www.stride3d.net",
        github_repo="stride3d/stride", sources=[gh("stride3d/stride")]),
    obj("wicked-engine", "Wicked Engine", "game_engine", "engine",
        "C++ engine featuring modern rendering techniques.", "https://wickedengine.net",
        github_repo="turanszkij/WickedEngine",
        sources=[gh("turanszkij/WickedEngine")]),
    obj("cryengine", "CryEngine", "game_engine", "engine",
        "Crytek's game engine.", "https://www.cryengine.com",
        sources=[notes("https://www.cryengine.com/marketplace?_iesign=1")]),
    obj("fyrox", "Fyrox", "game_engine", "engine",
        "Rust game engine with an editor.", "https://fyrox.rs",
        github_repo="FyroxEngine/Fyrox", sources=[gh("FyroxEngine/Fyrox")]),
    obj("gamemaker", "GameMaker", "game_engine", "engine",
        "2D game development platform.", "https://gamemaker.io",
        aliases=["GameMaker Studio 2"],
        sources=[rss("https://gamemaker.io/en/blog/rss", stype="official_blog")]),
    # ------------------------------------------------------- Engine: rendering
    obj("filament", "Filament", "rendering_engine", "engine",
        "Google's PBR rendering engine for Android/iOS/desktop/web.",
        "https://google.github.io/filament/", github_repo="google/filament",
        sources=[gh("google/filament")]),
    obj("bgfx", "bgfx", "rendering_engine", "engine",
        "Cross-platform rendering library with many graphics backends.",
        "https://github.com/bkaradzic/bgfx", github_repo="bkaradzic/bgfx",
        sources=[gh("bkaradzic/bgfx")]),
    obj("diligent-engine", "Diligent Engine", "rendering_engine", "engine",
        "Modern cross-platform rendering engine on top of its own RHI.",
        "https://diligentgraphics.com", github_repo="DiligentGraphics/DiligentCore",
        sources=[gh("DiligentGraphics/DiligentCore")]),
    obj("the-forge", "The Forge", "rendering_engine", "engine",
        "ConfettiFX rendering framework for cross-platform PC/console/mobile.",
        "https://github.com/ConfettiFX/The-Forge", github_repo="ConfettiFX/The-Forge",
        sources=[gh("ConfettiFX/The-Forge")]),
    obj("magnum", "Magnum", "rendering_engine", "engine",
        "Lightweight C++11/C++14 graphics middleware.", "https://magnum.graphics",
        github_repo="mosra/magnum", sources=[gh("mosra/magnum")]),
    obj("ogre-next", "OGRE-Next", "rendering_engine", "engine",
        "Threaded fork of OGRE 2.x.", "https://www.ogre3d.org",
        github_repo="OGRECave/ogre-next", aliases=["OGRE 2"],
        sources=[gh("OGRECave/ogre-next")]),
    obj("horde3d", "Horde3D", "rendering_engine", "engine",
        "Small open-source 3D rendering engine.", "https://horde3d.org",
        github_repo="horde3d/Horde3D", sources=[gh("horde3d/Horde3D")]),
    obj("falcor", "Falcor", "rendering_engine", "engine",
        "NVIDIA's real-time rendering research framework.",
        "https://github.com/NVIDIA/Falcor", github_repo="NVIDIA/Falcor",
        sources=[gh("NVIDIA/Falcor")]),
    obj("nvrhi", "NVRHI", "rendering_engine", "engine",
        "NVIDIA's abstraction layer over D3D12/Vulkan/Metal.",
        github_repo="NVIDIA-RTX/NVRHI", sources=[gh("NVIDIA-RTX/NVRHI")]),
    obj("sokol", "sokol", "rendering_engine", "engine",
        "Simple cross-platform headers including sokol_gfx.",
        github_repo="floooh/sokol", sources=[gh("floooh/sokol")]),
    obj("skia", "Skia", "rendering_engine", "engine",
        "Google's 2D graphics library used by Chrome/Android/Flutter.",
        "https://skia.org", github_repo="google/skia",
        sources=[gh_pr("google/skia", ["graphite", "gpu", "vulkan", "metal", "dawn", "webgpu", "renderer", "backend"])],
        ),
    obj("skia-graphite", "Skia Graphite", "rendering_engine", "engine",
        "Skia's next-generation GPU backend built on Dawn/WebGPU.",
        "https://skia.org/docs/user/modules/canvaskit", aliases=["Graphite"],
        sources=[]),
    obj("sdl-gpu", "SDL GPU", "rendering_engine", "engine",
        "SDL3's modern GPU abstraction API over D3D12/Vulkan/Metal.",
        "https://wiki.libsdl.org/SDL3/CategoryGPU", github_repo="libsdl-org/SDL",
        aliases=["SDL3 GPU"],
        sources=[gh("libsdl-org/SDL")]),
    obj("mesa", "Mesa", "rendering_engine", "engine",
        "Open-source OpenGL/Vulkan driver stack for Linux.",
        "https://www.mesa3d.org",
        sources=[notes("https://docs.mesa3d.org/relnotes.html"), rss(PHORONIX, stype="community")]),
    # ------------------------------------------------------- Engine: web
    obj("threejs", "Three.js", "web_engine", "engine",
        "The most widely used WebGL/WebGPU 3D library.", "https://threejs.org",
        github_repo="mrdoob/three.js", aliases=["three.js", "THREE"],
        sources=[gh("mrdoob/three.js")]),
    obj("babylonjs", "Babylon.js", "web_engine", "engine",
        "Web-first 3D engine by Microsoft with WebGPU support.",
        "https://www.babylonjs.com", github_repo="BabylonJS/Babylon.js",
        aliases=["Babylon"],
        sources=[gh("BabylonJS/Babylon.js"), rss("https://babylonjs.medium.com/feed", stype="official_blog")]),
    obj("playcanvas", "PlayCanvas", "web_engine", "engine",
        "WebGL/WebGPU engine and collaborative editor.", "https://playcanvas.com",
        github_repo="playcanvas/engine", sources=[gh("playcanvas/engine")]),
    obj("galacean", "Galacean Engine", "web_engine", "engine",
        "WebGL/WebGPU engine (formerly Alipay AntG/Cocos-origin Galacean).",
        "https://galacean.antgroup.com", github_repo="galacean/engine",
        aliases=["Galacean", "galacean engine"],
        sources=[gh("galacean/engine")]),
    obj("pixijs", "PixiJS", "web_engine", "engine",
        "The fastest 2D WebGL/WebGPU renderer for the web.", "https://pixijs.com",
        github_repo="pixijs/pixijs", aliases=["Pixi"],
        sources=[gh("pixijs/pixijs")]),
    obj("phaser", "Phaser", "web_engine", "engine",
        "2D HTML5 game framework.", "https://phaser.io",
        github_repo="phaserjs/phaser", sources=[gh("phaserjs/phaser")]),
    obj("cesiumjs", "CesiumJS", "web_engine", "engine",
        "3D geospatial engine for the web.", "https://cesium.com/platform/cesiumjs",
        github_repo="CesiumGS/cesium", aliases=["Cesium"],
        sources=[gh("CesiumGS/cesium")]),
    obj("maplibre-gl-js", "MapLibre GL JS", "web_engine", "engine",
        "Open-source WebGL map rendering library (Mapbox GL fork).",
        "https://maplibre.org", github_repo="maplibre/maplibre-gl-js",
        sources=[gh("maplibre/maplibre-gl-js")]),
    obj("react-three-fiber", "React Three Fiber", "web_engine", "engine",
        "React renderer for Three.js.", "https://docs.pmnd.rs",
        github_repo="pmndrs/react-three-fiber", aliases=["R3F"],
        sources=[gh("pmndrs/react-three-fiber")]),
    # ------------------------------------------------ Engine: platform runtime
    obj("angle", "ANGLE", "graphics_runtime", "engine",
        "Almost Native Graphics Layer Engine: OpenGL ES over Vulkan/D3D/Metal.",
        "https://chromium.googlesource.com/angle/angle", github_repo="google/angle",
        sources=[gh_pr("google/angle", ["vulkan", "metal", "d3d", "backend", "webgpu", "shader"])],
        ),
    obj("dawn", "Dawn", "graphics_runtime", "engine",
        "Chromium's WebGPU implementation in C++.", "https://dawn.googlesource.com/dawn",
        github_repo="google/dawn",
        sources=[gh_pr("google/dawn", ["webgpu", "vulkan", "metal", "d3d", "wgsl", "backend", "shader"])],
        ),
    obj("wgpu", "wgpu", "graphics_runtime", "engine",
        "Rust WebGPU implementation on Vulkan/Metal/D3D12/GL.",
        "https://wgpu.rs", github_repo="gfx-rs/wgpu",
        sources=[gh("gfx-rs/wgpu")]),
    obj("wgpu-native", "wgpu-native", "graphics_runtime", "engine",
        "Native bindings to wgpu for C/Python.", github_repo="gfx-rs/wgpu-native",
        sources=[gh("gfx-rs/wgpu-native")]),
    obj("flutter-impeller", "Flutter Impeller", "graphics_runtime", "engine",
        "Flutter's precompiled shader rendering engine.",
        "https://docs.flutter.dev/perf/impeller", github_repo="flutter/flutter",
        aliases=["Impeller"],
        sources=[gh_pr("flutter/flutter", ["impeller", "vulkan", "metal", "gpu"])],
        ),
    obj("qt-rhi", "Qt RHI", "graphics_runtime", "engine",
        "QRhi: Qt's rendering hardware interface over D3D/Vulkan/Metal/GL.",
        "https://doc.qt.io/qt-6/qrhi.html",
        sources=[rss("https://www.qt.io/blog/rss.xml", stype="official_blog")]),
    obj("chromium-graphics", "Chromium Graphics", "graphics_runtime", "engine",
        "Chromium's graphics stack (compositing, rasterization, GPU process).",
        "https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome/",
        sources=[rss(CHROME_BLOG, stype="official_blog")]),
    obj("webkit-graphics", "WebKit Graphics", "graphics_runtime", "engine",
        "WebKit's rendering and compositing stack.",
        "https://webkit.org", sources=[rss("https://webkit.org/blog/feed/", stype="official_blog")]),
    obj("android-hwui", "Android HWUI", "graphics_runtime", "engine",
        "Android's 2D UI rendering pipeline over OpenGL/Vulkan.",
        sources=[rss(ANDROID_BLOG, stype="official_blog")]),
    obj("realitykit", "RealityKit", "graphics_runtime", "engine",
        "Apple's AR/3D rendering framework.",
        "https://developer.apple.com/documentation/realitykit",
        sources=[notes("https://developer.apple.com/news/releases/")]),
    obj("scenekit", "SceneKit", "graphics_runtime", "engine",
        "Apple's 3D scene framework.",
        "https://developer.apple.com/documentation/scenekit", sources=[]),
    # ------------------------------------------------ Graphics API
    obj("vulkan", "Vulkan", "graphics_api", "graphics_api",
        "Khronos explicit cross-platform graphics & compute API.",
        "https://www.vulkan.org", github_repo="KhronosGroup/Vulkan-Docs",
        sources=[gh("KhronosGroup/Vulkan-Docs", 360), registry("https://registry.khronos.org/vulkan/"),
                 rss("https://www.khronos.org/blog/feed", stype="official_blog")]),
    obj("direct3d-12", "Direct3D 12", "graphics_api", "graphics_api",
        "Microsoft's explicit GPU API for Windows/Xbox.",
        "https://learn.microsoft.com/en-us/windows/win32/direct3d12/directx-12-programming-guide",
        aliases=["D3D12", "DirectX 12", "DirectX"],
        sources=[rss(DIRECTX_BLOG, stype="official_blog"),
                 notes("https://learn.microsoft.com/en-us/windows/win32/direct3d12/new-releases")]),
    obj("metal", "Metal", "graphics_api", "graphics_api",
        "Apple's low-level GPU API.", "https://developer.apple.com/metal/",
        sources=[notes("https://developer.apple.com/news/releases/")]),
    obj("opengl", "OpenGL", "graphics_api", "graphics_api",
        "Khronos cross-platform graphics API.",
        "https://www.opengl.org", github_repo="KhronosGroup/OpenGL-Registry",
        sources=[gh("KhronosGroup/OpenGL-Registry", 360), registry("https://registry.khronos.org/OpenGL/")]),
    obj("opengl-es", "OpenGL ES", "graphics_api", "graphics_api",
        "Khronos embedded/mobile graphics API.",
        "https://www.khronos.org/opengles/",
        sources=[registry("https://registry.khronos.org/OpenGL/")]),
    obj("webgpu", "WebGPU", "graphics_api", "graphics_api",
        "Next-generation web graphics & compute API.", "https://www.w3.org/TR/webgpu/",
        github_repo="gpuweb/gpuweb",
        sources=[gh_pr("gpuweb/gpuweb", ["webgpu", "wgsl", "spec", "constraint", "buffer", "texture"], 240),
                 rss(CHROME_BLOG, stype="official_blog")]),
    obj("webgl", "WebGL", "graphics_api", "graphics_api",
        "WebGL 1/2 standard based on OpenGL ES.",
        "https://www.khronos.org/webgl/", github_repo="KhronosGroup/WebGL",
        sources=[registry("https://registry.khronos.org/webgl/")]),
    obj("egl", "EGL", "graphics_api", "graphics_api",
        "Khronos interface between rendering APIs and windowing systems.",
        "https://www.khronos.org/egl", github_repo="KhronosGroup/EGL-Registry",
        sources=[registry("https://registry.khronos.org/EGL/")]),
    # ------------------------------------------------ Shader language / IR
    obj("glsl", "GLSL", "technology", "graphics_api",
        "OpenGL Shading Language.", "https://www.khronos.org/opengl/wiki/OpenGL_Shading_Language",
        sources=[registry("https://registry.khronos.org/OpenGL/")]),
    obj("hlsl", "HLSL", "technology", "graphics_api",
        "High-Level Shading Language for D3D.",
        "https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl",
        sources=[rss(DIRECTX_BLOG, stype="official_blog")]),
    obj("slang", "Slang", "tool", "graphics_api",
        "Shading language and compiler with module system, generics and multi-backend codegen.",
        "https://shader-slang.org", github_repo="shader-slang/slang",
        sources=[gh("shader-slang/slang"), rss("https://shader-slang.org/feed.xml", stype="official_blog")]),
    obj("wgsl", "WGSL", "technology", "graphics_api",
        "WebGPU Shading Language.", "https://www.w3.org/TR/WGSL/",
        sources=[gh_pr("gpuweb/gpuweb", ["wgsl"], 240)]),
    obj("metal-shading-language", "Metal Shading Language", "technology", "graphics_api",
        "MSL: shading language for Metal.",
        "https://developer.apple.com/metal/shading-language/", sources=[]),
    obj("spir-v", "SPIR-V", "technology", "graphics_api",
        "Khronos intermediate representation for shaders/compute kernels.",
        "https://www.khronos.org/spir/", github_repo="KhronosGroup/SPIRV-Registry",
        sources=[gh("KhronosGroup/SPIRV-Registry", 360)]),
    obj("dxil", "DXIL", "technology", "graphics_api",
        "DirectX Intermediate Language.",
        sources=[rss(DIRECTX_BLOG, stype="official_blog")]),
    # ------------------------------------------------ GPU & Platform
    obj("nvidia", "NVIDIA", "gpu_vendor", "gpu_platform",
        "GeForce/RTX GPU vendor; DLSS, Work Graphs, neural graphics.",
        "https://developer.nvidia.com", sources=[rss(NVIDIA_BLOG, stype="official_blog")]),
    obj("amd", "AMD", "gpu_vendor", "gpu_platform",
        "Radeon GPU vendor; FSR, GPUOpen.", "https://gpuopen.com",
        sources=[rss(GPUOPEN_BLOG, stype="official_blog")]),
    obj("intel", "Intel", "gpu_vendor", "gpu_platform",
        "Intel Arc/Xe GPU vendor; XeSS.",
        sources=[rss(PHORONIX, stype="community")]),
    obj("qualcomm-adreno", "Qualcomm / Adreno", "gpu_vendor", "gpu_platform",
        "Adreno mobile GPUs; Vulkan/mobile ray tracing enablement.",
        "https://developer.qualcomm.com",
        sources=[rss(PHORONIX, stype="community")]),
    obj("arm-mali", "ARM / Mali / Immortalis", "gpu_vendor", "gpu_platform",
        "Mali/Immortalis mobile GPUs.", "https://developer.arm.com",
        sources=[rss(PHORONIX, stype="community")]),
    obj("apple-gpu", "Apple GPU", "gpu_vendor", "gpu_platform",
        "Apple Silicon integrated GPUs.", sources=[]),
    obj("imagination-powervr", "Imagination / PowerVR", "gpu_vendor", "gpu_platform",
        "PowerVR GPUs.", "https://www.imaginationtech.com",
        sources=[rss("https://blog.imaginationtech.com/rss.xml", stype="official_blog")]),
    obj("samsung-xclipse", "Samsung / Xclipse", "gpu_vendor", "gpu_platform",
        "Samsung Xclipse GPUs (AMD RDNA licensed).", sources=[]),
    obj("broadcom-videocore", "Broadcom / VideoCore", "gpu_vendor", "gpu_platform",
        "Raspberry Pi VideoCore GPUs.", sources=[]),
    obj("android", "Android", "platform", "gpu_platform",
        "Android platform graphics stack.", "https://developer.android.com",
        sources=[rss(ANDROID_BLOG, stype="official_blog")]),
    obj("windows", "Windows", "platform", "gpu_platform",
        "Windows platform graphics stack (D3D12/WDDM).",
        sources=[rss(DIRECTX_BLOG, stype="official_blog")]),
    obj("linux", "Linux", "platform", "gpu_platform",
        "Linux platform graphics stack (Mesa/Wayland/DRM).",
        sources=[rss(PHORONIX, stype="community")]),
    obj("macos", "macOS", "platform", "gpu_platform", "Apple desktop platform.", sources=[]),
    obj("ios", "iOS", "platform", "gpu_platform", "Apple mobile platform.", sources=[]),
    obj("visionos", "visionOS", "platform", "gpu_platform", "Apple spatial computing platform.", sources=[]),
    obj("web-platform", "Web", "platform", "gpu_platform",
        "The web as a graphics platform.", sources=[rss(CHROME_BLOG, stype="official_blog")]),
    # ------------------------------------------------ DCC
    obj("blender", "Blender", "dcc", "content_pipeline",
        "Open-source 3D creation suite (Cycles, Eevee, Geometry Nodes).",
        "https://www.blender.org", github_repo="blender/blender",
        sources=[gh("blender/blender"), rss("https://www.blender.org/feed/", stype="official_blog"),
                 notes("https://developer.blender.org/docs/release_notes/")]),
    obj("houdini", "Houdini", "dcc", "content_pipeline",
        "SideFX procedural 3D application.", "https://www.sidefx.com",
        sources=[notes("https://www.sidefx.com/docs/houdini/news/index.html")]),
    obj("maya", "Maya", "dcc", "content_pipeline",
        "Autodesk 3D animation software.", "https://www.autodesk.com/products/maya",
        sources=[]),
    obj("3ds-max", "3ds Max", "dcc", "content_pipeline",
        "Autodesk 3D modeling/rendering software.", "https://www.autodesk.com/products/3ds-max",
        sources=[]),
    obj("substance-3d", "Substance 3D", "dcc", "content_pipeline",
        "Adobe's texturing/material suite (Painter, Designer).",
        "https://www.adobe.com/products/substance3d.html",
        sources=[notes("https://helpx.adobe.com/substance-3d/release-notes.html")]),
    # ------------------------------------------------ Tooling
    obj("renderdoc", "RenderDoc", "tool", "tooling",
        "Frame debugger and graphics debugger for D3D/Vulkan/OpenGL/Metal.",
        "https://renderdoc.org", github_repo="baldurk/renderdoc",
        sources=[gh("baldurk/renderdoc")]),
    obj("nsight-graphics", "Nsight Graphics", "tool", "tooling",
        "NVIDIA's GPU application profiling/debugging tool.",
        sources=[rss(NVIDIA_BLOG, stype="official_blog")]),
    obj("nsight-systems", "Nsight Systems", "tool", "tooling",
        "NVIDIA's whole-system profiling tool.",
        sources=[rss(NVIDIA_BLOG, stype="official_blog")]),
    obj("pix", "PIX", "tool", "tooling",
        "Microsoft's Xbox/Windows graphics debugger and profiler.",
        sources=[rss(DIRECTX_BLOG, stype="official_blog")]),
    obj("rgp", "Radeon GPU Profiler", "tool", "tooling",
        "AMD's low-level GPU profiler.", "https://gpuopen.com/rgp/",
        sources=[rss(GPUOPEN_BLOG, stype="official_blog")]),
    obj("rra", "Radeon Raytracing Analyzer", "tool", "tooling",
        "AMD's ray tracing performance analyzer.", "https://gpuopen.com/rra/",
        sources=[rss(GPUOPEN_BLOG, stype="official_blog")]),
    obj("intel-gpa", "Intel GPA", "tool", "tooling",
        "Intel Graphics Performance Analyzers.", sources=[]),
    obj("agi", "Android GPU Inspector", "tool", "tooling",
        "Google's Android GPU profiling tool.", "https://gpuinspector.dev",
        sources=[rss(ANDROID_BLOG, stype="official_blog")]),
    obj("arm-performance-studio", "Arm Performance Studio", "tool", "tooling",
        "Arm's mobile GPU profiling suite (Streamline).", sources=[]),
    obj("xcode-gpu-tools", "Xcode GPU Tools", "tool", "tooling",
        "Apple's Metal debugger and GPU profiler.", sources=[]),
    obj("tracy", "Tracy Profiler", "tool", "tooling",
        "Real-time nanosecond resolution frame profiler.", "https://github.com/wolfpld/tracy",
        github_repo="wolfpld/tracy", sources=[gh("wolfpld/tracy")]),
    obj("superluminal", "Superluminal", "tool", "tooling",
        "Performance profiler for C++ by Molecular Matters.", "https://www.superluminal.eu", sources=[]),
    obj("gfxreconstruct", "gfxreconstruct", "tool", "tooling",
        "Graphics API capture/replay for Vulkan/D3D12.",
        github_repo="LunarG/gfxreconstruct", sources=[gh("LunarG/gfxreconstruct")]),
    obj("dxc", "DXC", "tool", "tooling",
        "HLSL compiler producing DXIL/SPIR-V.", github_repo="microsoft/DirectXShaderCompiler",
        sources=[gh("microsoft/DirectXShaderCompiler")]),
    obj("shaderc", "shaderc", "tool", "tooling",
        "GLSL/HLSL to SPIR-V compiler library.", github_repo="google/shaderc",
        sources=[gh("google/shaderc")]),
    obj("spirv-tools", "SPIRV-Tools", "tool", "tooling",
        "SPIR-V assembler/optimizer/validator.", github_repo="KhronosGroup/SPIRV-Tools",
        sources=[gh("KhronosGroup/SPIRV-Tools")]),
    obj("spirv-cross", "SPIRV-Cross", "tool", "tooling",
        "SPIR-V to GLSL/HLSL/MSL decompiler.", github_repo="KhronosGroup/SPIRV-Cross",
        sources=[gh("KhronosGroup/SPIRV-Cross")]),
    # ------------------------------------------------ Standard / Asset
    obj("gltf", "glTF", "standard", "standard",
        "Khronos runtime 3D asset delivery format.", "https://www.khronos.org/gltf/",
        github_repo="KhronosGroup/glTF",
        sources=[gh("KhronosGroup/glTF", 360), registry("https://registry.khronos.org/glTF/")]),
    obj("openusd", "OpenUSD", "standard", "standard",
        "Universal Scene Description.", "https://openusd.org",
        github_repo="PixarAnimationStudios/OpenUSD",
        sources=[gh("PixarAnimationStudios/OpenUSD")]),
    obj("materialx", "MaterialX", "standard", "standard",
        "Open standard for rich material representation.",
        github_repo="AcademySoftwareFoundation/MaterialX",
        sources=[gh("AcademySoftwareFoundation/MaterialX")]),
    obj("openpbr", "OpenPBR", "standard", "standard",
        "Open surface shading model standard (MaterialX-based).",
        github_repo="AcademySoftwareFoundation/OpenPBR",
        sources=[gh("AcademySoftwareFoundation/OpenPBR")]),
    obj("ktx", "KTX", "standard", "standard",
        "Khronos texture container (KTX2/Basis Universal supercompression).",
        github_repo="KhronosGroup/KTX-Software",
        sources=[gh("KhronosGroup/KTX-Software")]),
    obj("basis-universal", "Basis Universal", "standard", "standard",
        "GPU texture codec (transcodable compressed textures).",
        github_repo="BinomialLLC/basis_universal",
        sources=[gh("BinomialLLC/basis_universal")]),
    obj("draco", "Draco", "standard", "standard",
        "Google's mesh/point-cloud compression library.",
        github_repo="google/draco", sources=[gh("google/draco")]),
    obj("meshoptimizer", "meshoptimizer", "standard", "standard",
        "Mesh processing/compression library (zeux).",
        github_repo="zeux/meshoptimizer", sources=[gh("zeux/meshoptimizer")]),
    obj("openexr", "OpenEXR", "standard", "standard",
        "HDR image format.", github_repo="AcademySoftwareFoundation/openexr",
        sources=[gh("AcademySoftwareFoundation/openexr")]),
    obj("openimageio", "OpenImageIO", "standard", "standard",
        "Image I/O library.", github_repo="AcademySoftwareFoundation/OpenImageIO",
        sources=[gh("AcademySoftwareFoundation/OpenImageIO")]),
    obj("mdl", "MDL", "standard", "standard",
        "NVIDIA Material Definition Language.", "https://github.com/NVIDIA/MDL-SDK",
        sources=[gh("NVIDIA/MDL-SDK")]),
    obj("osl", "Open Shading Language", "standard", "standard",
        "OSL shading language.", github_repo="AcademySoftwareFoundation/OpenShadingLanguage",
        sources=[gh("AcademySoftwareFoundation/OpenShadingLanguage")]),
    obj("directstorage", "DirectStorage", "technology", "gpu_platform",
        "Windows GPU-accelerated asset streaming API.",
        sources=[rss(DIRECTX_BLOG, stype="official_blog")]),
    obj("vulkan-sdk", "Vulkan SDK", "technology", "graphics_api",
        "LunarG's Vulkan SDK (validation layers, tools).", "https://vulkan.lunarg.com",
        sources=[]),
    # ------------------------------------------------ Technology (rendering tech)
    obj("dlss", "DLSS", "technology", "rendering_tech",
        "NVIDIA's deep-learning super sampling and frame generation.",
        sources=[rss(NVIDIA_BLOG, stype="official_blog")]),
    obj("fsr", "FSR", "technology", "rendering_tech",
        "AMD FidelityFX Super Resolution.", sources=[rss(GPUOPEN_BLOG, stype="official_blog")]),
    obj("xess", "XeSS", "technology", "rendering_tech",
        "Intel Xe Super Sampling.", sources=[rss(PHORONIX, stype="community")]),
    obj("metalfx", "MetalFX", "technology", "rendering_tech",
        "Apple's upscaling framework.", sources=[]),
    obj("gpu-driven-rendering", "GPU Driven Rendering", "technology", "rendering_tech",
        "GPU-driven culling, draw generation and scene management.", sources=[]),
    obj("virtual-geometry", "Virtual Geometry", "technology", "rendering_tech",
        "Nanite-like virtualized micro-polygon geometry.", sources=[]),
    obj("mesh-shading", "Mesh Shading", "technology", "rendering_tech",
        "Mesh/task shader pipelines.", sources=[]),
    obj("ray-tracing", "Ray Tracing", "technology", "rendering_tech",
        "Real-time and offline ray tracing.", sources=[]),
    obj("real-time-gi", "Real-time Global Illumination", "technology", "rendering_tech",
        "Real-time GI techniques (DDGI, probes, ReSTIR GI).", sources=[]),
    obj("neural-rendering", "Neural Rendering", "technology", "rendering_tech",
        "Neural shading, neural materials, neural compression.", sources=[]),
    obj("3d-gaussian-splatting", "3D Gaussian Splatting", "technology", "rendering_tech",
        "3DGS radiance field rendering and its engineering ecosystem.",
        aliases=["3DGS", "Gaussian Splatting"], sources=[]),
]


TOPICS: list[dict] = [
    {"id": "rendering-architecture", "name": "Rendering Architecture", "parent": None,
     "keywords": ["rhi", "render graph", "frame graph", "render pipeline", "backend", "descriptor", "bindless", "multithreaded rendering", "async compute"]},
    {"id": "geometry", "name": "Geometry", "parent": None,
     "keywords": ["mesh", "geometry", "culling", "lod", "meshlet", "mesh shader", "nanite", "vertex", "compression"]},
    {"id": "lighting-shading", "name": "Lighting & Shading", "parent": None,
     "keywords": ["pbr", "lighting", "global illumination", "gi", "path tracing", "ray tracing", "restir", "shadow", "material"]},
    {"id": "gpu-execution", "name": "GPU Execution", "parent": None,
     "keywords": ["gpu", "work graph", "compute", "barrier", "scheduling", "command buffer"]},
    {"id": "resource-asset", "name": "Resource & Asset", "parent": None,
     "keywords": ["texture", "asset", "streaming", "gltf", "usd", "compression", "format"]},
    {"id": "image-reconstruction", "name": "Image Reconstruction", "parent": None,
     "keywords": ["upscaling", "dlss", "fsr", "xess", "metalfx", "frame generation", "denoising", "temporal"]},
    {"id": "neural-graphics", "name": "Neural Graphics", "parent": None,
     "keywords": ["neural", "machine learning", "nerf", "gaussian splatting", "3dgs", "radiance field", "neural texture", "neural shading"]},
    {"id": "platform-runtime", "name": "Platform & Runtime", "parent": None,
     "keywords": ["android", "ios", "windows", "linux", "macos", "web", "driver", "runtime", "browser"]},
    {"id": "webgpu", "name": "WebGPU", "parent": "platform-runtime",
     "keywords": ["webgpu", "wgsl", "dawn", "wgpu"]},
    {"id": "vulkan", "name": "Vulkan", "parent": "platform-runtime",
     "keywords": ["vulkan", "spir-v", "vk"]},
    {"id": "mobile-rendering", "name": "Mobile Rendering", "parent": "platform-runtime",
     "keywords": ["mobile", "adreno", "mali", "immortalis", "phone", "android"]},
    {"id": "rhi", "name": "RHI", "parent": "rendering-architecture",
     "keywords": ["rhi", "render hardware interface", "abstraction layer"]},
    {"id": "render-graph", "name": "Render Graph", "parent": "rendering-architecture",
     "keywords": ["render graph", "frame graph"]},
    {"id": "bindless", "name": "Bindless", "parent": "rendering-architecture",
     "keywords": ["bindless", "descriptor heap", "descriptor indexing"]},
    {"id": "gpu-driven", "name": "GPU Driven", "parent": "rendering-architecture",
     "keywords": ["gpu driven", "gpu culling", "indirect draw", "work graph"]},
    {"id": "mesh-shader", "name": "Mesh Shader", "parent": "geometry",
     "keywords": ["mesh shader", "task shader", "meshlet"]},
    {"id": "virtual-geometry", "name": "Virtual Geometry", "parent": "geometry",
     "keywords": ["nanite", "virtual geometry", "micropolygon", "cluster"]},
    {"id": "ray-tracing", "name": "Ray Tracing", "parent": "lighting-shading",
     "keywords": ["ray tracing", "rt", "rtx", "bvhs"]},
    {"id": "real-time-gi", "name": "Real-time GI", "parent": "lighting-shading",
     "keywords": ["global illumination", "ddgi", "probe", "radiance cache", "restir"]},
    {"id": "3dgs", "name": "3D Gaussian Splatting", "parent": "neural-graphics",
     "keywords": ["gaussian splatting", "3dgs", "splat"]},
    {"id": "neural-rendering", "name": "Neural Rendering", "parent": "neural-graphics",
     "keywords": ["neural rendering", "neural shading", "coop vector", "neural material"]},
    {"id": "neural-texture-compression", "name": "Neural Texture Compression", "parent": "neural-graphics",
     "keywords": ["neural texture compression", "ntc"]},
    {"id": "temporal-upscaling", "name": "Temporal Upscaling", "parent": "image-reconstruction",
     "keywords": ["upscaling", "tsr", "super resolution", "taa"]},
    {"id": "frame-generation", "name": "Frame Generation", "parent": "image-reconstruction",
     "keywords": ["frame generation", "frame interpolation"]},
    {"id": "shader-language", "name": "Shader Language", "parent": None,
     "keywords": ["slang", "hlsl", "glsl", "wgsl", "msl", "shader compiler", "spir-v", "dxil"]},
    {"id": "asset-pipeline", "name": "Asset Pipeline", "parent": "resource-asset",
     "keywords": ["asset pipeline", "dcc", "blender", "importer", "exporter"]},
    {"id": "graphics-tooling", "name": "Graphics Tooling", "parent": None,
     "keywords": ["renderdoc", "profiler", "debugger", "capture", "replay", "nsight", "pix"]},
    {"id": "gpu-driver", "name": "GPU Driver", "parent": "platform-runtime",
     "keywords": ["driver", "mesa", "radv", "anv", "nvk", "wddm"]},
]


def main() -> None:
    OBJECTS_DIR.mkdir(parents=True, exist_ok=True)
    TOPICS_DIR.mkdir(parents=True, exist_ok=True)
    for old in list(OBJECTS_DIR.glob("*.yaml")) + list(TOPICS_DIR.glob("*.yaml")):
        old.unlink()
    for o in OBJECTS:
        cfg = dict(o)
        path = OBJECTS_DIR / f"{cfg['id']}.yaml"
        path.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    for t in TOPICS:
        cfg = dict(t)
        path = TOPICS_DIR / f"{cfg['id']}.yaml"
        path.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    print(f"objects: {len(OBJECTS)} -> {OBJECTS_DIR}")
    print(f"topics: {len(TOPICS)} -> {TOPICS_DIR}")


if __name__ == "__main__":
    main()
